#%RAML 1.0
title: Sample API

/accounts/{accId}:
   description: this is mule
   get:
   post:
      responses:
        200:
          body:
           application/json:
             example:
                {
                 "firstName":"shubham",
                 "lastName":"saraswat",
                 "address":"shivaji nagar",
                 "organization":"TCS",
                }

   